name: Code Style

on:
  push:
    branches: [ main ]
    paths:
      - '**.php'
      - '.php-cs-fixer.php'
      - 'composer.json'
      - '.github/workflows/code-style.yml'
  pull_request:
    branches: [ main ]
    paths:
      - '**.php'
      - '.php-cs-fixer.php'
      - 'composer.json'

jobs:
  php-cs-fixer:
    name: PHP CS Fixer
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: json, mbstring
          coverage: none
          tools: composer:v2

      - name: Install Dependencies
        run: composer install --prefer-dist --no-interaction

      - name: Check & fix styling
        run: |
          vendor/bin/php-cs-fixer fix --config=.php-cs-fixer.php --allow-risky=yes --dry-run --diff
        continue-on-error: false
